### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by hugovk**
Also flake8.

No functional changes to everywordbot.py

You can enable Travis CI on your account here: https://travis-ci.org/profile
And optionally Coveralls for coverage here: https://coveralls.io/repos/new

### CODE REVIEW

**Comment by aparrish** [comment]
cool, thanks!

**Comment by aparrish** [comment]
also feel free to do a PR that adds a "Contributors" section to the README and add yourself to it. (I'll do this at some point if you don't but it might take a while for me to get around to it!)

**Comment by hugovk** [comment]
What do you think about enabling Coveralls for your repo? It's free, and you can see the coverage reports online, for example: https://coveralls.io/r/hugovk/everywordbot (There's also a badge for the README, if you want.)

Enable here: https://coveralls.io/repos/new

Edit: Seems to be a bug at coveralls.io preventing this right now: https://github.com/lemurheavy/coveralls-public/issues/517

**Comment by aparrish** [comment]
enabled and added the badge!

**Pull request merged**
